# Generated by Django 4.2 on 2023-05-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Course Ratings'},
        ),
        migrations.RenameField(
            model_name='courserating',
            old_name='enrolled_time',
            new_name='review_time',
        ),
    ]
