# Generated by Django 4.2 on 2023-05-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_studentfavoritecourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '8. Course Ratings'},
        ),
    ]
