# Generated by Django 4.2 on 2023-05-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_studentassignemnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignemnt',
            name='student_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
