# Generated by Django 4.2 on 2023-05-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_quiz_quizquestions_coursequiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': '13. Course Quiz'},
        ),
        migrations.RenameField(
            model_name='coursequiz',
            old_name='notif_created_time',
            new_name='add_time',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='notif_for',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='notif_subject',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='notifread_status',
        ),
    ]
