# Generated by Django 4.2 on 2023-05-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_course_course_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
