# Generated by Django 4.2 on 2023-05-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_student_login_via_otp_teacher_login_via_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='login_via_otp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='otp_digit',
        ),
    ]
