# Generated by Django 4.2 on 2023-06-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_teacher_facebook_url_teacher_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(max_length=20)),
                ('profile_img', models.ImageField(upload_to='about_us_imgs/')),
            ],
        ),
    ]
