# Generated by Django 4.2 on 2023-06-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': '19. About Us Content'},
        ),
    ]
