# Generated by Django 4.2 on 2023-06-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_teacher_login_via_otp_teacher_otp_digit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='login_via_otp',
        ),
    ]
