# Generated by Django 4.2 on 2023-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_teacher_otp_digit_teacher_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp_digit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='verify_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_imgs/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profile_imgs/'),
        ),
    ]
